### ISSUE TITLE
Can't seem to get it working

### ISSUE THREAD

**Issue by skawaguchi** [Workiva/karma-jspm#49]
Sorry if this is because of my setup or my conf, but it seems that I can't this running. Here's my [code](https://github.com/skawaguchi/karma-jspm-test). Any help would be appreciated.

**Comment by crissdev** [comment]
Not working :boom: 
A sample repo would be enough to help people out.

**Comment by matthewharwood** [comment]
@crissdev https://github.com/matthewharwood/angular2-dynamic/tree/unittest I got it working.. Just `npm install` `npm start` `karma start` I cant find where I saw the error but the problem is in jspm hard coding the world "base" somewhere or something .  ` "paths": {    "*": "*.js",}` this has to be `*.js` Sorry for lack of reference.

**Comment by crissdev** [comment]
Thanks @matthewharwood.
